name: NungXX



on: workflow_dispatch



jobs:

  build:



    runs-on: windows-2022

    timeout-minutes: 999

    steps:

    - uses: actions/checkout@v2

    - name: Mendownload Ngrok.

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/sefart/new/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/sefart/new/main/loop.bat -OutFile loop.bat

        



    - name: Mengextract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ke Akun Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}



    - name: Mengaktifkan Akses RDP.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        

        

    - name: Membuat Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region us 3389"'

    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 255 SSD.

      run: cmd /c start.bat

    - name: RDP Berhasil Dibuat Nung!! 

      run: cmd /c loop.bat

